name: Generate REST API Client

on:
  workflow_dispatch:  # Manuel tetikleme için
    inputs:
      swagger_content:
        description: 'Swagger/OpenAPI JSON content'
        required: true
        type: string
      target_language:
        description: 'Target language'
        required: true
        default: 'csharp'
        type: choice
        options:
        - csharp
        - java
        - nodejs

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Test
      run: echo "Workflow working!"
